.pragma library

// English UI strings, keyed by the Russian source text used in the QML and
// model code. A missing key falls back to the Russian text.
var EN = {
  "\nПКМ: ": "\nRMB: ",
  " (обход ": " (bypass ",
  " (показаны первые 5000)": " (first 5000 shown)",
  " · DoH в браузере или DNSOverTLS в systemd-resolved": " · DoH in the browser or DNSOverTLS in systemd-resolved",
  " · СКМ: приложение": " · MMB: app",
  " · без перезапуска": " · no restart",
  " · включён": " · on",
  " · как база": " · same as baseline",
  " · лучшая": " · best",
  " · лучше базы": " · better than baseline",
  " · обход перезапущен": " · bypass restarted",
  " · отброшено ": " · dropped ",
  " · перезапусков ": " · restarts ",
  " · проверено ": " · checked ",
  " · стратегия ": " · strategy ",
  " · хуже базы": " · worse than baseline",
  " без перезапуска обхода": " without restarting the bypass",
  " дн назад": " d ago",
  " доменов": " domains",
  " доменов корректны": " domains valid",
  " записей": " entries",
  " и перезапустить обход": " and restart the bypass",
  " из ": " of ",
  " мин назад": " min ago",
  " мс": " ms",
  " с перезапуском обхода": " with a bypass restart",
  " строк": " lines",
  " строк журнала": " log lines",
  " строк, отброшено ": " lines, dropped ",
  " установлен": " installed",
  " ч назад": " h ago",
  " частично": " partially",
  "# Опции: --lua-desync, --payload, --out-range и др. (см. man nfqws2)\n": "# Options: --lua-desync, --payload, --out-range and more (see man nfqws2)\n",
  "# Пример:\n": "# Example:\n",
  "# Своя стратегия — секции nfqws2: [TCP_HTTP], [TCP_TLS], [TCP_GENERIC], [QUIC]\n": "# Own strategy — nfqws2 sections: [TCP_HTTP], [TCP_TLS], [TCP_GENERIC], [QUIC]\n",
  "# пример:\n# 1.2.3.0/24\n# 2001:db8::/32\n": "# example:\n# 1.2.3.0/24\n# 2001:db8::/32\n",
  "# пример:\nexample.com\n# sub.example.org\n": "# example:\nexample.com\n# sub.example.org\n",
  "$1 файлов в порядке": "$1 files intact",
  ") — открыть приложение": ") — open the app",
  ") — сейчас ": ") — now ",
  "): откройте Движок → Журнал": "): open Engine → Log",
  ", активна": ", active",
  ", выбрана": ", selected",
  ", лучшая": ", best",
  ", развёрнуто": ", expanded",
  ", свёрнуто": ", collapsed",
  "11 проверок = адреса YouTube, Discord, Google, Cloudflare по TLS. QUIC-пробы не учитываются.": "11 checks = YouTube, Discord, Google, Cloudflare addresses over TLS. QUIC probes are not counted.",
  "CIRCULAR-КОНФИГ": "CIRCULAR CONFIG",
  "Circular-конфиг создан": "Circular config built",
  "Ctrl+1…6 — вкладки\nCtrl+T — вкл/выкл\n/ — поиск": "Ctrl+1…6 — tabs\nCtrl+T — on/off\n/ — search",
  "DNS не отвечает": "DNS not responding",
  "DNS-серверы не определены": "DNS servers not detected",
  "Enter включит обход": "Enter turns the bypass on",
  "Enter выключит обход": "Enter turns the bypass off",
  "Enter откроет приложение (o)": "Enter opens the app (o)",
  "Enter откроет список · h/l тоже открывает": "Enter opens the list · h/l opens it too",
  "Enter проверит доступность (c)": "Enter checks availability (c)",
  "Enter установит движок": "Enter installs the engine",
  "Hosts включён": "Hosts on",
  "Hosts включён: ": "Hosts on: ",
  "Hosts выключен": "Hosts off",
  "IP-сети (ipset)": "IP networks (ipset)",
  "IP-сети включены для игрового фильтра": "IP networks enabled for the game filter",
  "TCP и UDP": "TCP and UDP",
  "TUN omarchy-xray выключен, трафик идёт мимо туннеля": "omarchy-xray TUN is off, traffic bypasses the tunnel",
  "Zapret2 · нет связи с менеджером": "Zapret2 · no connection to the manager",
  "Zapret2 включён при входе": "Zapret2 turned on at login",
  "Zapret2 загружается…": "Zapret2 loading…",
  "Zapret2 удалён из системы": "Zapret2 removed from the system",
  "Zapret2: Обход": "Zapret2: Bypass",
  "Zapret2: Открыть": "Zapret2: Open",
  "blockcheck2 запущен: это может занять долго": "blockcheck2 started: this may take a while",
  "blockcheck2 остановлен": "blockcheck2 stopped",
  "curl установлен": "curl installed",
  "j/k строка · h/l действие · Enter применить · Home/End края": "j/k row · h/l action · Enter apply · Home/End ends",
  "nfqws2 + Lua. Скачивает релиз, сверяет sha256, спрашивает пароль; прошлая версия остаётся рядом.": "nfqws2 + Lua. Downloads the release, verifies sha256, asks for the password; the previous version stays alongside.",
  "nftables установлен": "nftables installed",
  "omarchy-zapret2 завершился с кодом ": "omarchy-zapret2 exited with code ",
  "t вкл/выкл · c проверить · o открыть · s стратегия · ? скрыть": "t on/off · c check · o open · s strategy · ? hide",
  "wl-copy не найден": "wl-copy not found",
  "zapret из AUR и другие NFQUEUE не запущены": "no AUR zapret or other NFQUEUE running",
  "«Вместе с данными» стирает и свои списки и стратегии": "\"With data\" also erases your own lists and strategies",
  "Адреса Discord-серверов в /etc/hosts · нужен пароль": "Discord server addresses in /etc/hosts · needs password",
  "БЫСТРЫЙ ПОДБОР": "QUICK PICK",
  "Без обхода": "No bypass",
  "Введите домен": "Enter a domain",
  "Весь журнал": "Full log",
  "Включать при входе": "Turn on at login",
  "Включить": "Turn on",
  "Включить (t)": "Turn on (t)",
  "Включить обход": "Turn on bypass",
  "Включить обход (Ctrl+T)": "Turn on bypass (Ctrl+T)",
  "Включить обход без новой проверки": "Turn on bypass without a new check",
  "Включить обход со стратегией ": "Turn on bypass with strategy ",
  "Включён": "On",
  "Вместе с данными": "With data",
  "Восстановить": "Restore",
  "Восстановить из вставленного текста": "Restore from the pasted text",
  "Все стратегии (": "All strategies (",
  "Вставить пример": "Insert example",
  "Вставить пример записей в редактор": "Insert example entries into the editor",
  "Вставьте в конец ~/.config/hypr/bindings.lua, заменив KEY (первая — окно, вторая — обход)": "Append to the end of ~/.config/hypr/bindings.lua, replacing KEY (first — window, second — bypass)",
  "Вставьте текст копии": "Paste backup text",
  "Вставьте текст, путь или ссылку": "Paste text, a path or a link",
  "Встроенные списки уже покрывают YouTube и Discord. Добавьте свой домен, только если он не открывается.": "Built-in lists already cover YouTube and Discord. Add your own domain only if it does not open.",
  "Встроенные: IP-исключения": "Built-in: IP exclusions",
  "Встроенные: IP-сети": "Built-in: IP networks",
  "Встроенные: YouTube/Google": "Built-in: YouTube/Google",
  "Встроенные: исключения": "Built-in: exclusions",
  "Встроенные: общий список": "Built-in: general list",
  "Всё открывается": "Everything opens",
  "Выбрана стратегия ": "Strategy selected: ",
  "Выключен": "Off",
  "Выключен — голосовой трафик идёт без подмены": "Off — voice traffic goes without faking",
  "Выключите VPN-туннель (omarchy-xray TUN) — поиск через туннель бессмыслен": "Turn off the VPN tunnel (omarchy-xray TUN) — searching through the tunnel is pointless",
  "Выключите VPN-туннель (omarchy-xray TUN): поиск через туннель бессмыслен": "Turn off the VPN tunnel (omarchy-xray TUN): searching through the tunnel is pointless",
  "Выключить": "Turn off",
  "Выключить (t)": "Turn off (t)",
  "Выключить обход": "Turn off bypass",
  "Выключить обход (Ctrl+T)": "Turn off bypass (Ctrl+T)",
  "Выполняется": "Running",
  "Выполняется: ": "Running: ",
  "ГЛУБОКИЙ ПОИСК: BLOCKCHECK2": "DEEP SEARCH: BLOCKCHECK2",
  "ГОРЯЧИЕ КЛАВИШИ": "HOTKEYS",
  "Голос Discord": "Discord voice",
  "Готово": "Done",
  "Готово. ": "Done. ",
  "Готовые наборы доменов в «Мои: сайты»; поддомены включаются сами.": "Ready-made domain sets are in \"Mine: sites\"; subdomains are included automatically.",
  "ДВИЖОК ZAPRET2 НЕ УСТАНОВЛЕН": "ZAPRET2 ENGINE NOT INSTALLED",
  "ДВИЖОК: ": "ENGINE: ",
  "ДИАГНОСТИКА": "DIAGNOSTICS",
  "ДОСТУПНО ОБНОВЛЕНИЕ ZAPRET2": "ZAPRET2 UPDATE AVAILABLE",
  "ДОСТУПНОСТЬ": "AVAILABILITY",
  "Движок": "Engine",
  "Движок ": "Engine ",
  "Движок zapret2 ещё не установлен. Установка скачает официальный релиз bol-van/zapret2, проверит sha256 и один раз спросит пароль.": "The zapret2 engine is not installed yet. Setup downloads the official bol-van/zapret2 release, verifies sha256 and asks for the password once.",
  "Движок не установлен": "Engine not installed",
  "Движок, списки и стратегии — раз в сутки, в фоне": "Engine, lists and strategies — once a day, in the background",
  "Действия": "Actions",
  "Диагностика": "Diagnostics",
  "Для части доменов нужен blockcheck2": "Some domains need blockcheck2",
  "Добавить адреса Discord-серверов из Flowseal в /etc/hosts (спросит пароль)": "Add Discord server addresses from Flowseal to /etc/hosts (asks for password)",
  "Доступность": "Availability",
  "Доступны обновления Zapret2: ": "Zapret2 updates available: ",
  "Дублирована как ": "Duplicated as ",
  "Дублировать": "Duplicate",
  "Если Discord не грузится; закройте его перед очисткой": "If Discord does not load; close it before clearing",
  "Если игра не подключается; нагружает сильнее.": "If a game does not connect; heavier load.",
  "Есть обновления: ": "Updates available: ",
  "Ещё не проверялось": "Not checked yet",
  "ЖУРНАЛ СЛУЖБЫ": "SERVICE LOG",
  "Журнал": "Log",
  "ЗАПИСИ": "ENTRIES",
  "Загружено: ": "Loaded: ",
  "Загрузить пресеты Flowseal заново": "Reload Flowseal presets",
  "Загрузить списки Flowseal заново": "Reload Flowseal lists",
  "Загрузка…": "Loading…",
  "Закрыть": "Close",
  "Закрыть просмотр (Esc)": "Close preview (Esc)",
  "Замер без обхода…": "Measuring without bypass…",
  "Запуск…": "Starting…",
  "Запустите автоподбор, чтобы найти рабочую стратегию": "Run autopick to find a working strategy",
  "Запустить автоподбор": "Run autopick",
  "Запустить быстрый подбор (1–3 минуты)": "Run quick pick (1–3 minutes)",
  "Запустить глубокий поиск": "Start deep search",
  "Запустить подбор": "Run pick",
  "Запустить поиск": "Start search",
  "ИНСТРУМЕНТЫ": "TOOLS",
  "Игровой фильтр": "Game filter",
  "Идёт поиск… ": "Searching… ",
  "Изменит /etc/hosts, нужен пароль": "Changes /etc/hosts, needs password",
  "Изменить": "Edit",
  "Изменить /etc/hosts (спросит пароль)": "Change /etc/hosts (asks for password)",
  "Изменить свою стратегию": "Edit own strategy",
  "Импорт": "Import",
  "Импортировать": "Import",
  "Имя (необязательно)": "Name (optional)",
  "Имя:": "Name:",
  "Имя: латиница, цифры и дефисы": "Name: latin letters, digits and hyphens",
  "КЛАВИШИ": "KEYS",
  "Команда не выполнилась (код ": "Command failed (code ",
  "Команда не выполнилась: откройте Движок → Журнал": "Command failed: open Engine → Log",
  "Кэш DNS очищен": "DNS cache flushed",
  "Кэш Discord": "Discord cache",
  "Кэш Discord очищен": "Discord cache cleared",
  "Кэш Discord очищен: ": "Discord cache cleared: ",
  "Любой IP": "Any IP",
  "Менеджер не запустился: нужен /usr/bin/python3": "Manager did not start: /usr/bin/python3 is required",
  "Мои: IP-исключения": "Mine: IP exclusions",
  "Мои: IP-сети (через обход)": "Mine: IP networks (via bypass)",
  "Мои: исключения (без обхода)": "Mine: exclusions (no bypass)",
  "Мои: сайты (через обход)": "Mine: sites (via bypass)",
  "Нажмите ещё раз для удаления": "Click again to remove",
  "Найти стратегию": "Find a strategy",
  "Настройки": "Settings",
  "Настройки, списки и стратегии — в буфер обмена": "Settings, lists and strategies — to the clipboard",
  "Не больше 10 доменов": "No more than 10 domains",
  "Не использовать": "Do not use",
  "Не найден python3 — установите: omarchy pkg add python": "python3 not found — install it: omarchy pkg add python",
  "Не установлен": "Not installed",
  "Неизвестная ошибка": "Unknown error",
  "Некорректный домен: ": "Invalid domain: ",
  "Нет VPN-туннеля": "No VPN tunnel",
  "Нет других zapret": "No other zapret",
  "Нет прав: запустите установку (пароль)": "No permission: run setup (password)",
  "Нет связи": "No connection",
  "Новая": "New",
  "Новые списки применятся после перезапуска": "New lists apply after a restart",
  "Нужен bind для blockcheck2: omarchy pkg add bind": "bind is needed for blockcheck2: omarchy pkg add bind",
  "Нужен пакет bind: omarchy pkg add bind": "Package bind is needed: omarchy pkg add bind",
  "Нужно дополнительно проверить домены через blockcheck2": "Some domains need an extra check with blockcheck2",
  "ОСНОВНОЕ": "GENERAL",
  "Обзор": "Overview",
  "Обновить": "Refresh",
  "Обновить движок (zapret2)": "Update engine (zapret2)",
  "Обновить движок zapret2 до последнего релиза (спросит пароль)": "Update the zapret2 engine to the latest release (asks for password)",
  "Обновить журнал": "Refresh log",
  "Обновить из Flowseal": "Update from Flowseal",
  "Обновить плагин": "Update plugin",
  "Обновлений нет": "No updates",
  "Обход DPI, ": "DPI bypass, ",
  "Обход включён": "Bypass on",
  "Обход включён · ЛКМ: выключить": "Bypass on · LMB: turn off",
  "Обход выключен": "Bypass off",
  "Обход выключен · ЛКМ: включить": "Bypass off · LMB: turn on",
  "Обход и для IPv6-соединений": "Bypass for IPv6 connections too",
  "Обход на время поиска выключается": "Bypass is off during the search",
  "Обход не нужен": "Bypass not needed",
  "Обход остановился с ошибкой. Откройте Zapret2 → Движок → Логи": "The bypass stopped with an error. Open Zapret2 → Engine → Log",
  "Обход, ": "Bypass, ",
  "Оставить /etc/hosts как есть": "Leave /etc/hosts as is",
  "Оставить всё как есть": "Leave everything as is",
  "Оставить стратегию": "Keep strategy",
  "Останавливает обход; удаляет /opt, юниты, polkit. Данные остаются.": "Stops the bypass; removes /opt, units, polkit. Data stays.",
  "Остановить": "Stop",
  "Остановить глубокий поиск": "Stop deep search",
  "Остановить подбор": "Stop pick",
  "Открыть": "Open",
  "Открыть Движок": "Open Engine",
  "Открыть Движок: диагностика и журнал": "Open Engine: diagnostics and log",
  "Открыть Подбор": "Open Pick",
  "Открыть вкладку Движок: обновление плагина": "Open the Engine tab: plugin update",
  "Открыть вкладку Подбор": "Open the Pick tab",
  "Открыть диагностику и журнал (вкладка Движок)": "Open diagnostics and log (Engine tab)",
  "Открыть копию в редакторе своих стратегий": "Open the copy in the own-strategy editor",
  "Открыть приложение": "Open app",
  "Открыть приложение (o)": "Open app (o)",
  "Отмена": "Cancel",
  "Отменено: пароль не введён": "Cancelled: no password entered",
  "Очистить": "Clear",
  "Очистить и сохранить": "Clear and save",
  "Очистить кэш": "Clear cache",
  "Ошибка": "Error",
  "Ошибка: ": "Error: ",
  "ПЕРВЫЙ ЗАПУСК": "FIRST RUN",
  "ПЕРЕХОД": "NAVIGATION",
  "Перебор стратегий…": "Trying strategies…",
  "Перезапустить обход после сохранения": "Restart the bypass after saving",
  "Плагин и системная копия": "Plugin and system copy",
  "По списку": "From list",
  "По умолчанию": "Default",
  "Повторить": "Retry",
  "Повторить диагностику": "Run diagnostics again",
  "Подбор": "Pick",
  "Подобрать стратегию для вашей сети": "Pick a strategy for your network",
  "Подождите: ": "Please wait: ",
  "Подтвердить": "Confirm",
  "Показать": "Show",
  "Показать все строки": "Show all lines",
  "Показать все строки журнала": "Show all log lines",
  "Показать план": "Show plan",
  "Показать текст пресета": "Show preset text",
  "Показать число доменов в круговой конфигурации": "Show the number of domains in the circular config",
  "Полный пресет Flowseal: правится через копию как свою.": "Full Flowseal preset: edit it through a copy of your own.",
  "Порты TCP": "TCP ports",
  "Порты UDP": "UDP ports",
  "Последняя проверка была для ": "The last check was for ",
  "Построить конфиг": "Build config",
  "Пресеты Flowseal": "Flowseal presets",
  "Применить": "Apply",
  "Применить ": "Apply ",
  "Проверить": "Check",
  "Проверить домен": "Check domain",
  "Проверить домен…": "Check a domain…",
  "Проверить доступность": "Check availability",
  "Проверить доступность (c)": "Check availability (c)",
  "Проверить доступность с текущей стратегией": "Check availability with the current strategy",
  "Проверить и сохранить как свою стратегию": "Check and save as own strategy",
  "Проверить пресеты для сайтов и построить круговую конфигурацию": "Check presets for sites and build a circular config",
  "Проверить свои домены через пробел или запятую (до 10)": "Check your own domains, separated by spaces or commas (up to 10)",
  "Проверка других обходов": "Checking other bypasses",
  "Проверка зависимостей": "Checking dependencies",
  "Проверка обновлений ещё не выполнялась": "Update check has not run yet",
  "Проверка показывает, что обход не нужен — включить принудительно": "The check shows the bypass is not needed — turn it on anyway",
  "Проверка прав": "Checking privileges",
  "Проверка пресетов…": "Checking presets…",
  "Проверка системы": "Checking the system",
  "Проверка…": "Checking…",
  "Проверок ещё не было": "No checks yet",
  "Проверяет пресеты для сайтов и строит ротацию лучших.": "Checks presets for sites and builds a rotation of the best.",
  "Проверяет стратегии по очереди; первая рабочая побеждает. 1–3 минуты, без пароля.": "Tries strategies one by one; the first working one wins. 1–3 minutes, no password.",
  "Проверять обновления ежедневно": "Check for updates daily",
  "РЕЗЕРВНАЯ КОПИЯ": "BACKUP",
  "Резервная копия восстановлена": "Backup restored",
  "СЕРВИСЫ": "SERVICES",
  "СЕТЬ И DNS": "NETWORK AND DNS",
  "СТРАТЕГИИ": "STRATEGIES",
  "Сайты открываются и так.": "Sites open without it.",
  "Сбросить кэш DNS (resolvectl flush-caches)": "Flush the DNS cache (resolvectl flush-caches)",
  "Свои": "Own",
  "Своя стратегия nfqws2: имя и текст пресета": "Own nfqws2 strategy: name and preset text",
  "Секции [TCP_*]/[QUIC]; опции --lua-desync, --payload, --out-range. Блобы: tls_google, quic_google, http_iana и др.": "Sections [TCP_*]/[QUIC]; options --lua-desync, --payload, --out-range. Blobs: tls_google, quic_google, http_iana and more.",
  "Системная часть обновлена": "System part updated",
  "Системная часть плагина; спросит пароль. Настройки, списки и стратегии останутся.": "The plugin's system part; asks for the password. Settings, lists and strategies stay.",
  "Системные файлы": "System files",
  "Скачивает релиз bol-van/zapret2, сверяет sha256 и кладёт в /opt/omarchy-zapret2. Пароль — один раз.": "Downloads the bol-van/zapret2 release, verifies sha256 and puts it in /opt/omarchy-zapret2. Password once.",
  "Скопировано": "Copied",
  "Скопировано файлов: ": "Files copied: ",
  "Скопировать": "Copy",
  "Скопировать Lua-сниппет в буфер": "Copy the Lua snippet to the clipboard",
  "Скопировать как свою": "Copy as own",
  "Скопировать команду установки bind (установка — вручную)": "Copy the bind install command (install it yourself)",
  "Скопировать команду: omarchy pkg add bind": "Copy the command: omarchy pkg add bind",
  "Скопировать краткую диагностику без адресов и доменов": "Copy a short diagnostics report without addresses or domains",
  "Скопировать резервную копию в буфер обмена": "Copy the backup to the clipboard",
  "Скрыть действия": "Hide actions",
  "Скрыть импорт": "Hide import",
  "Скрыть служебные строки": "Hide service lines",
  "Скрыть стратегии хуже базы": "Hide strategies worse than baseline",
  "Скрыть хуже базы": "Hide worse than baseline",
  "Служба": "Service",
  "Сначала установите движок (вкладка Обзор → Установить)": "Install the engine first (Overview tab → Install)",
  "Сниппет для bindings.lua": "Snippet for bindings.lua",
  "Совместимый": "Compatible",
  "Совместимый — мягкая подмена для звонков Discord": "Compatible — soft faking for Discord calls",
  "Сохранено": "Saved",
  "Сохранено как ": "Saved as ",
  "Сохранено: ": "Saved: ",
  "Сохранить": "Save",
  "Сохранить копию своей стратегии под новым именем": "Save a copy of your own strategy under a new name",
  "Сохранить найденное как свою стратегию": "Save the finding as own strategy",
  "Сохранить свою стратегию": "Save own strategy",
  "Сохранить список (": "Save list (",
  "Списки": "Lists",
  "Списки обновлены: ": "Lists updated: ",
  "Список": "List",
  "Список пуст — так и должно быть": "The list is empty — as it should be",
  "Список только для чтения": "Read-only list",
  "Ссылка должна начинаться с http(s)://": "The link must start with http(s)://",
  "Стандартный": "Standard",
  "Стандартный — подмена нулями, звонки могут не работать": "Standard — zero faking, calls may not work",
  "Стратегии": "Strategies",
  "Стратегии обновлены": "Strategies updated",
  "Стратегии обновлены: ": "Strategies updated: ",
  "Стратегия импортирована": "Strategy imported",
  "Стратегия сохранена": "Strategy saved",
  "Стратегия удалена": "Strategy removed",
  "Стратегия: ": "Strategy: ",
  "Текст из экспорта": "Text from an export",
  "Текст стратегии, путь к файлу или ссылка http(s); сохраняется как своя (my-*)": "Strategy text, a file path or an http(s) link; saved as your own (my-*)",
  "Текст, путь к файлу или ссылка http(s)": "Text, a file path or an http(s) link",
  "Только важное": "Important only",
  "Только ошибки, предупреждения и перезапуски": "Only errors, warnings and restarts",
  "Точно удалить?": "Remove for sure?",
  "УДАЛЕНИЕ": "REMOVAL",
  "Убрать записи из /etc/hosts (спросит пароль)": "Remove the entries from /etc/hosts (asks for password)",
  "Удалить": "Remove",
  "Удалить Zapret2": "Remove Zapret2",
  "Удалить все записи и сохранить пустой список": "Remove all entries and save an empty list",
  "Удалить движок и настройки плагина": "Remove the engine and plugin settings",
  "Удалить и свои списки и стратегии": "Also remove your own lists and strategies",
  "Удалить кэш Discord": "Delete the Discord cache",
  "Удалить свою стратегию": "Delete own strategy",
  "Удалить, данные оставить": "Remove, keep data",
  "Установить": "Install",
  "Установить движок zapret2": "Install the zapret2 engine",
  "Установить движок zapret2 (t)": "Install the zapret2 engine (t)",
  "Установить движок zapret2 (спросит пароль один раз)": "Install the zapret2 engine (asks for the password once)",
  "Установить обновление системной части плагина (спросит пароль)": "Install the plugin's system part update (asks for password)",
  "Установка": "Setup",
  "Установка…": "Installing…",
  "ФЕЙКИ": "FAKES",
  "Фейк для голоса Discord": "Fake for Discord voice",
  "Фейк для игр": "Fake for games",
  "Что означают проверки": "What the checks mean",
  "Шаг ": "Step ",
  "Шаг 1 из 3: установите движок zapret2 (один пароль).": "Step 1 of 3: install the zapret2 engine (one password).",
  "Шаг 2 из 3: запустите автоподбор стратегии (1–3 минуты).": "Step 2 of 3: run strategy autopick (1–3 minutes).",
  "Шаг 3 — готово: обход включён или не нужен.": "Step 3 — done: the bypass is on or not needed.",
  "Шелл включает обход после входа в систему": "The shell turns the bypass on after login",
  "Экспорт": "Export",
  "автоподбор": "autopick",
  "быстрый": "quick",
  "быстрый — минуты": "quick — minutes",
  "в порядке: ": "ok: ",
  "вкл": "on",
  "включение": "turning on",
  "включить": "turn on",
  "включён": "on",
  "включён TUN omarchy-xray: трафик идёт в туннель, обход не применяется": "omarchy-xray TUN is on: traffic goes into the tunnel, the bypass does not apply",
  "встроенные": "bundled",
  "всё открывается": "everything opens",
  "выкл": "off",
  "выключен": "off",
  "выключение": "turning off",
  "выключить": "turn off",
  "движок": "engine",
  "движок ": "engine ",
  "движок установлен": "engine installed",
  "диагностика": "diagnostics",
  "для blockcheck2": "for blockcheck2",
  "домен или IP/CIDR на строку": "a domain or IP/CIDR per line",
  "домены через пробел": "domains separated by spaces",
  "дублирование стратегии": "duplicating strategy",
  "запрос пароля через polkit доступен": "password prompt via polkit available",
  "запустите установку": "run setup",
  "импорт": "import",
  "импорт стратегии": "importing strategy",
  "логи": "logs",
  "лучшая": "best",
  "например 1024-65535": "e.g. 1024-65535",
  "например home": "e.g. home",
  "настройка": "settings",
  "не открываются": "do not open",
  "не проверялась": "not checked",
  "не сохранено": "not saved",
  "не установлен": "not installed",
  "необязательно: ": "optional: ",
  "нужно действие: ": "needs action: ",
  "нужны для blockcheck2: omarchy pkg add bind": "needed for blockcheck2: omarchy pkg add bind",
  "обновление": "update",
  "обновление движка": "engine update",
  "обновление списков": "lists update",
  "обновление стратегий": "strategies update",
  "обход был ": "bypass was ",
  "обычный": "standard",
  "обычный — до часа и дольше": "standard — up to an hour or longer",
  "остановка blockcheck": "stopping blockcheck",
  "остановлена": "stopped",
  "очистка кэша DNS": "flushing DNS cache",
  "очистка кэша Discord": "clearing Discord cache",
  "ошибка": "error",
  "ошибка TLS (DPI?)": "TLS error (DPI?)",
  "ошибка: ": "error: ",
  "перезапусков": "restarts",
  "плагин обновлён: установите обновление системной части": "plugin updated: install the system part update",
  "по проверке ": "by the check ",
  "пресетов": "presets",
  "проверка": "check",
  "проверка обновлений": "update check",
  "работает": "running",
  "с поддержкой HTTP/3": "with HTTP/3 support",
  "сервис": "service",
  "сервисы": "services",
  "системная копия совпадает с плагином": "system copy matches the plugin",
  "соединение отклонено": "connection refused",
  "соединение сброшено": "connection reset",
  "создание circular-конфига": "building circular config",
  "сохранение находки": "saving finding",
  "сохранение списка": "saving list",
  "сохранение стратегии": "saving strategy",
  "списки": "lists",
  "стратегии": "strategies",
  "таймаут": "timeout",
  "только чтение": "read-only",
  "только что": "just now",
  "удаление": "removal",
  "удаление стратегии": "removing strategy",
  "установите $1": "install $1",
  "установите nftables/curl/polkit": "install nftables/curl/polkit",
  "установка": "setup",
  "установлены, нужны для blockcheck2": "installed, needed for blockcheck2",
  "устарело · ": "stale · ",
  "чтение": "reading",
  "экспорт": "export",
  "● — выбрана · ±N к базе без обхода": "● — selected · ±N vs. no-bypass baseline",
  "⚠ хуже, чем без обхода": "⚠ worse than no bypass",
  "Язык": "Language",
  "Язык интерфейса": "Interface language",
  "Доступно обновление Zapret2": "Zapret2 update available",
  "СОСТОЯНИЕ": "STATUS",
  "через пробел или запятую, до 10": "space or comma separated, up to 10",
  "не запустилась": "did not start",
  "Пресет ": "Preset ",
  "Круговой конфиг": "Circular config",
  "обход на время проверки выключается": "the bypass is off while checking",
  "Проверяет каждый пресет на сайтах из проверки и строит ротацию лучших. 3–5 минут.": "Tests every preset against the check sites and builds a rotation of the best. 3–5 minutes.",
  "Построить": "Build",
  "В ротации доменов: ": "Domains in rotation: ",
  "План ещё не построен": "No plan built yet",
  "Готово: доменов в ротации ": "Done: domains in rotation ",
  "Нужен blockcheck2: ": "blockcheck2 needed: "
}
