test("backup sizes", () => {
  eq(Model.isValidBackupSize(1), true)
  eq(Model.isValidBackupSize(2 * 1024 * 1024), true)
  eq(Model.isValidBackupSize(0), false)
  eq(Model.isValidBackupSize(-5), false)
  eq(Model.isValidBackupSize(2 * 1024 * 1024 + 1), false)
  eq(Model.isValidBackupFileSize(0), true)
  eq(Model.isValidBackupFileSize(512 * 1024), true)
  eq(Model.isValidBackupFileSize(512 * 1024 + 1), false)
})
