test("service titles and state", () => {
  eq(Model.serviceTitle("telegram"), "Telegram")
  eq(Model.serviceTitle("whatsapp"), "WhatsApp")
  eq(Model.serviceTitle("twitter"), "X (Twitter)")
  eq(Model.serviceTitle("rutracker"), "RuTracker")
  eq(Model.serviceTitle("unknown-x"), "unknown-x")
  eq(Model.serviceStateLabel(true), "включён")
  eq(Model.serviceStateLabel(false), "выключен")
  eq(Model.serviceStateLabel(undefined), "выключен")
})
