test("import source kind", () => {
  eq(Model.importSourceKind(""), "empty")
  eq(Model.importSourceKind("  "), "empty")
  eq(Model.importSourceKind("https://example.com/s.txt"), "url")
  eq(Model.importSourceKind("http://x/y"), "url")
  eq(Model.importSourceKind("ftp://x/y"), "text")
  eq(Model.importSourceKind("~/my-strategy.txt"), "file")
  eq(Model.importSourceKind("/tmp/s.txt"), "file")
  eq(Model.importSourceKind("rel/path.txt"), "file")
  eq(Model.importSourceKind("[TCP_TLS]\n--lua-desync=fake"), "text")
  eq(Model.isImportableUrl("https://a.b/c"), true)
  eq(Model.isImportableUrl("http://a.b/c"), true)
  eq(Model.isImportableUrl("ftp://a.b/c"), false)
  eq(Model.isImportableUrl("just text"), false)
})

test("strategy name ok", () => {
  eq(Model.strategyNameOk("my-home"), true)
  eq(Model.strategyNameOk("my-a1-b2"), true)
  eq(Model.strategyNameOk("home"), false)
  eq(Model.strategyNameOk("fs-general"), false)
  eq(Model.strategyNameOk("my-"), false)
  eq(Model.strategyNameOk("my-BAD"), false)
  eq(Model.strategyNameOk("my-" + "a".repeat(29)), true)
  eq(Model.strategyNameOk("my-" + "a".repeat(30)), false)
})
